### PR TITLE
possible fix entity nbt saving for paper

### PR DESCRIPTION
**Pull request by amadeusmz**

### CODE REVIEW

**Comment by Paul19988** [comment]
Has this been tested?

**Comment by amadeusmz** [comment]
> Has this been tested?

yes, the world can now be saved normally, no more console spam
https://i.imgur.com/aINvDGj.png

**Comment by CDFN** [comment]
I'm wondering why there is only fix for 1.16.5. Error doesn't occurr in other versions such as 1.17?

**Comment by amadeusmz** [comment]
> I'm wondering why there is only fix for 1.16.5. Error doesn't occurr in other versions such as 1.17?

My server is running 1.16.5 so I only fix it. Currently I can't test other versions.

**Comment by Paul19988** [comment]
> I'm wondering why there is only fix for 1.16.5. Error doesn't occurr in other versions such as 1.17?

1.17 made changes to how entities are saved and loaded.

**Pull request merged**
