### PR TITLE
Initial 1.18 Work

### PR DESCRIPTION
**Pull request by Owen1212055**
This implements initial 1.18 support, thanks to the heavy initial workload being done by PaulBGD.

File links:
Check #new-builds channel and look for the 1.18 branch (https://discord.com/channels/741733106930810950/741741550383398942/956527537670979606)

You can also build it yourself if you want.

This has required a lot of work and changes, feel free to support me ❤️ 
https://github.com/sponsors/Owen1212055?frequency=one-time

### CODE REVIEW

**Comment by PaulBGD** [comment]
We are still missing some class modifiers:

- CraftServer.addWorld (can then re-add the CraftServer.addWorld call to the 1.18 adapter)
- MinecraftServer.getGameMode
- MinecraftServer.loadWorlds (needed for default worlds to be slime worlds presumably)
- MobSpawnerTrader.tickRaids
- PersistentBase.saveData

I also just pushed a fix for section indexing and some final cleanups from my admittedly messy branch. Beyond that, I think it might be worth investigating adding support for 1.17 negative section indexes, as it does support them and it is relatively easy to copy support from 1.18. I only did not add them because I was not sure how upgrading formats would be handled.

Tag me if you need anything else, if I come across any bugs before this is merged I will push to my branch and give this PR a heads up :)

**Comment by PaulBGD** [comment]
https://github.com/Paul19988/Advanced-Slime-World-Manager/blob/23ad9909e5262babde55d4b7b708f5ab97b9e4cc/slimeworldmanager-classmodifier/src/main/resources/slimeworldmanager-classmodifierapi.txt

I forgot about this, should probably be fixed before merging. I could not figure out how to inject the classes for the API into all the classloaders without having it as its own JAR, then I could not figure out how to include a dependency as a literal JAR resource, then I also could not figure out how to get gradle to add a JAR as a resource without renaming the extension to txt. It is all very awful and if anyone is aware of how to fix this with 1.18's new resource system, please do.

**Comment by Owen1212055** [comment]
The latest commit should fix chunk saving for nonempty sections. Heightmaps that aren't needed after worldgen will not be saved anymore as well.

**Comment by Owen1212055** [comment]
Fix for spigot, and also add it so light is properly loaded for PAPER-only servers.
Before the light data was simply thrown away...

**Review by Blaxor — COMMENTED** [review]
Tested and is working for now

**Comment by galexrt** [comment]
I had some issues running on Paper 1.18.1 build 200, though I haven't yet checked if this also happens on Spigot and others.

I encountered an out of bounds exception in `v1_9SlimeWorldFormat.java`.

```
[17:52:52 INFO]: [SWM] Loading world SWMWORLD2.
[17:52:52 ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Index 23 out of bounds for length 23 initializing SlimeWorldManager v${project.version} (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 23 out of bounds for length 23
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunkSectionsNew(v1_9SlimeWorldFormat.java:358) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunks(v1_9SlimeWorldFormat.java:285) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:130) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:252) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:196) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:82) ~[slimeworldmanager-plugin.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-200]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I'm new to Slime Format but adding +1 to the chunk array size seemed fine from the code flow and fixed the issue.

I have done the following changes to get it working https://github.com/Paul19988/Advanced-Slime-World-Manager/compare/1.18...galexrt:1.18_fix (please ignore the Java version and `.gitignore` changes).

**Comment by Owen1212055** [comment]
> I had some issues running on Paper 1.18.1 build 200, though I haven't yet checked if this also happens on Spigot and others.
> 
> 
> 
> I encountered an out of bounds exception in `v1_9SlimeWorldFormat.java`.
> 
> 
> 
> ```
> 
> [17:52:52 INFO]: [SWM] Loading world SWMWORLD2.
> 
> [17:52:52 ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Index 23 out of bounds for length 23 initializing SlimeWorldManager v${project.version} (Is it up to date?)
> 
> java.lang.ArrayIndexOutOfBoundsException: Index 23 out of bounds for length 23
> 
> 	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunkSectionsNew(v1_9SlimeWorldFormat.java:358) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunks(v1_9SlimeWorldFormat.java:285) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:130) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:252) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:196) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:82) ~[slimeworldmanager-plugin.jar:?]
> 
> 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[paper-1.18.1.jar:git-Paper-200]
> 
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-200]
> 
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-200]
> 
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-200]
> 
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> 
> ```
> 
> 
> 
> I'm new to Slime Format but adding +1 to the chunk array size seemed fine from the code flow and fixed the issue.
> 
> 
> 
> I have done the following changes to get it working https://github.com/Paul19988/Advanced-Slime-World-Manager/compare/1.18...galexrt:1.18_fix (please ignore the Java version and `.gitignore` changes).

- Can I have more info as to how this world was created? Is it brand new? Or was it an old 1.17 world that was updated to 1.18? Can I have a download?

**Comment by galexrt** [comment]
I just tested with a new generated and then imported map:

```
> mv create testworld normal
[23:33:11 INFO]: CONSOLE: Starting creation of world 'testworld'...
[23:33:11 INFO]: [Multiverse-Core] Loading World & Settings - 'testworld' - Env: NORMAL - Type: NORMAL
[23:33:16 INFO]: Preparing start region for dimension minecraft:testworld
[23:33:16 INFO]: Preparing spawn area: 0%
[23:33:16 INFO]: Time elapsed: 203 ms
[23:33:16 INFO]: CONSOLE: Complete!
> mv unload testworld
[23:33:34 INFO]: [Multiverse-Core] World 'testworld' was unloaded from Multiverse.
[23:33:35 INFO]: [Multiverse-Core] World 'testworld' was unloaded from Bukkit.
[23:33:35 INFO]: CONSOLE: Unloaded world 'testworld'!
> swm import testworld mongodb testworld
[23:33:36 INFO]: SWM >> WARNING: The Slime Format is meant to be used on tiny maps, not big survival worlds. It is recommended to trim your world by using the Prune MCEdit tool to ensure you don't save more chunks than you want to.
[23:33:36 INFO]:
[23:33:36 INFO]: SWM >> NOTE: This command will automatically ignore every chunk that doesn't contain any blocks.
[23:33:36 INFO]:
[23:33:36 INFO]: SWM >> If you are sure you want to continue, type again this command.
> swm import testworld mongodb testworld
[23:33:37 INFO]: SWM >> Importing world testworld into data source mongodb...
[23:33:39 INFO]: SWM >> World testworld imported successfully in 1016ms. Remember to add it to the worlds config file before loading it.
```

I have added the testworld to the config with `loadOnStartup: true` and server Restart:

```
[23:42:19 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:104}] to 127.0.0.1:27017
[23:42:19 INFO]: [SWM] Loading world testworld.
[23:42:19 ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Index 23 out of bounds for length 23 initializing SlimeWorldManager v${project.version} (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 23 out of bounds for length 23
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunkSectionsNew(v1_9SlimeWorldFormat.java:358) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunks(v1_9SlimeWorldFormat.java:285) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:130) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:252) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:196) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:82) ~[slimeworldmanager-plugin.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-200]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-200]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Maybe the importer is broken? If you have a "correct" slime world for me to test I can do that

**Comment by Owen1212055** [comment]
Yea, this appears to be an issue with the importer.

**Comment by galexrt** [comment]
I have tried to use the standalone importer jar build using this branch, the standalone importer jar doesn't work due to this error:

```
$ java -jar slimeworldmanager-importer/build/libs/slimeworldmanager-importer.jar
no main manifest attribute, in slimeworldmanager-importer/build/libs/slimeworldmanager-importer.jar
```

I haven't worked with Gradle enough to know how to fix the main class being set in the importer jar file.

I'm currently trying to see if I'm able to find the issue in the `/swm import` command.

**Comment by PaulBGD** [comment]
I haven't been following this too much, but I never updated the importer and didn't add the manifest to the importer's gradle config. Ideally the conversion code should be moved to another module so it can be reused by both the importer and the plugin, which is why I didn't bother updating it yet.

**Comment by galexrt** [comment]
No worries, I'm just trying to see if I'm able to track down the issue of the exception I'm getting with loading a freshly imported world using this branch for 1.18.x support.

I might have figured out my issue now, the `v1_9SlimeWorldFormat.java` does a calculation of the length of the `SlimeChunkSection` array, but from some debugging the `sectionCount` should be used as far as I can tell (e.g., where the calculation for a freshly imported world lead to a size of `23` and `sectionCount: 24` which fixes the exception for me).

```diff
diff --git a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
index 74d2ffa..30e9f08 100644
--- a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
+++ b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
@@ -313,7 +313,7 @@ public class v1_9SlimeWorldFormat implements SlimeWorldReader {
         int minSectionY = dataStream.readInt();
         int maxSectionY = dataStream.readInt();
         int sectionCount = dataStream.readInt();
-        SlimeChunkSection[] chunkSectionArray = new SlimeChunkSection[(maxSectionY - minSectionY)+1];
+        SlimeChunkSection[] chunkSectionArray = new SlimeChunkSection[sectionCount];

         for (int i = 0; i < sectionCount; i++) {
             int y = dataStream.readInt();
```

So with the above patch, I haven't encountered the exception with imported worlds anymore and so far any other issues yet on 1.18.1 (running Paper 1.18.1 builds 200, 204 and 207).

**Comment by Owen1212055** [comment]
By freshly imported, do you mean imported from a normal Minecraft world? Trying to figure it out as this seems to just be an issue with the importer. If so, can u provide the world you use? Thanks!

**Comment by galexrt** [comment]
@Owen1212055 by freshly imported I'm talking a newly created Minecraft world,  running the `/swm import` command on it and then loading it on server start.

I have used the steps from here https://github.com/Paul19988/Advanced-Slime-World-Manager/pull/97#issuecomment-1045311876 with the patch I posted I'm not getting the exception anymore.

Edit: I can upload one of the new worlds if you want. I know that Slime World Format isn't really good to be used for normal survival worlds but for testing a new "vanilla" world should be enough?

**Comment by Owen1212055** [comment]
@galexrt Took a look and yea, it seems thats a valid fix there. Try to see if it works. (Updated download link)

**Comment by Owen1212055** [comment]
@galexrt If possible, see if these changes break your fix.

This caused issues where chunk counts don't match the actual number of sections there could be. Your error is showing that there are more chunk sections than the world fits.

**Comment by Owen1212055** [comment]
Added support for 1.18.2

**Comment by Owen1212055** [comment]
Added world overriding, seems to work fine on 1.18.1.

**Comment by galexrt** [comment]
@Owen1212055 so far I have not encountered issues with the chunk count for new worlds, thanks!

I think I stumbled upon an issue with the "default world" during testing of the latest commits.

Having set `level-name=testworld` and configured the "custom" built AdvancedSlimeWorldManager to load `testworld` world on startup.

* On Paper 1.18.1 build 216: Works fine the map is loaded correctly, but it seems that if the world has `readOnly: false` the world is (not) unlocked in the database on server shutdown (command used `/stop` and `/restart`; tested with mongodb source only so far).
* On Paper 1.18.2 build 232: The server loads the world from the data source `[SWM] World testworld loaded in 133ms.`, but when a player joins on it it is a vanilla survival world. Checking the servers root directory, a world named `testworld` seems to be generated (even after deleting and then restarting the server). Server logs contain the following SWM debug output:
	```
	[20:58:08 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:115}] to 127.0.0.1:27017
	[20:58:08 INFO]: [SWM] Loading world testworld.
	[20:58:08 INFO]: [SWM] World testworld loaded in 133ms.
	[...]
	[20:58:11 INFO]: Preparing level "testworld"
	[20:58:11 INFO]: [SlimeWorldManager] [STDOUT] INJECTING: ServerLevel[testworld] null null
	[...]
	[20:58:11 INFO]: [SlimeWorldManager] Enabling SlimeWorldManager v${project.version}
	[...]
	```

I hope that this info can help with the ongoing work on v1.18.* support. If I should test any new changes, please let me know.

**Comment by Owen1212055** [comment]
@galexrt 

Thanks for your testing and detailed report ❤️! 

Fixed your first issue by ensuring that locked worlds are unlocked when stopping the server.
Additionally, the 1.18.2 issue, seems like a field got switched so the world wasn't being passed in (so it wasn't being loaded).

All fixed!

**Comment by galexrt** [comment]
@Owen1212055 I have just noticed that my previous tests regarding the chunk count exception were done with a build that had my custom patch (see below) applied. I'm still getting the exception with the sectionCount array in the `v1_9SlimeWorldFormat.java`.

I have now tried a build of the current state of the `1.18` branch (commit: f135874deef9fc50cb5b1916c9e232764b51bab9) and am getting the below exception with a newly imported world:

```
[14:18:01 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:2, serverValue:2}] to 127.0.0.1:27017
[14:18:01 INFO]: [SWM] Loading world testworld.
[14:18:01 INFO]: [SWM] World testworld loaded in 108ms.
[14:18:01 INFO]: [SWM] Loading world buildtest.
[14:18:01 ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] Index 23 out of bounds for length 23 initializing SlimeWorldManager v${project.version} (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 23 out of bounds for length 23
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunkSectionsNew(v1_9SlimeWorldFormat.java:358) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.readChunks(v1_9SlimeWorldFormat.java:285) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.impl.v1_9SlimeWorldFormat.deserializeWorld(v1_9SlimeWorldFormat.java:130) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.loaders.slime.SlimeWorldReaderRegistry.readWorld(SlimeWorldReaderRegistry.java:50) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorld(SWMPlugin.java:262) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.loadWorlds(SWMPlugin.java:206) ~[slimeworldmanager-plugin.jar:?]
	at com.grinderwolf.swm.plugin.SWMPlugin.onLoad(SWMPlugin.java:83) ~[slimeworldmanager-plugin.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-232]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-232]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-232]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-232]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Using your branch with the patch below works fine for importing and loading maps (only tested with Paper 1.18.1 and 1.18.2) for the servers I have it running on. The patch also includes a small change to the world version check (`WorldImporter.java`) to treat 1.18.2 worlds the same as 1.18.1 worlds during import:

```patch
diff --git a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
index ce6e493..30e9f08 100644
--- a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
+++ b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/loaders/slime/impl/v1_9SlimeWorldFormat.java
@@ -313,7 +313,7 @@ public class v1_9SlimeWorldFormat implements SlimeWorldReader {
         int minSectionY = dataStream.readInt();
         int maxSectionY = dataStream.readInt();
         int sectionCount = dataStream.readInt();
-        SlimeChunkSection[] chunkSectionArray = new SlimeChunkSection[maxSectionY - minSectionY];
+        SlimeChunkSection[] chunkSectionArray = new SlimeChunkSection[sectionCount];

         for (int i = 0; i < sectionCount; i++) {
             int y = dataStream.readInt();
diff --git a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/world/importer/WorldImporter.java b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/world/importer/WorldImporter.java
index 28ceb84..19a8bc6 100644
--- a/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/world/importer/WorldImporter.java
+++ b/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/world/importer/WorldImporter.java
@@ -42,8 +42,8 @@ public class WorldImporter {
             return 0x06; // 1.16 world
         } else if (dataVersion <= 2730) {
             return 0x07;
-        } else if (dataVersion <= 2865) {
-            return 0x08; // 1.18 world
+        } else if (dataVersion <= 2975) {
+            return 0x08; // 1.18.1 and 1.18.2 world
         } else {
             throw new UnsupportedOperationException("Unsupported world version: " + dataVersion);
         }
```

(This commit/patch can be found here https://github.com/galexrt/Advanced-Slime-World-Manager/commit/8f3aeb72d84cb93aca880ad773d07054dce1df05)

**Comment by Owen1212055** [comment]
@galexrt Hmm thanks for the heads up. I'll need to look into this as this issue is only seen when importing worlds using the importer. When implementing the fix it causes issues with normal worlds.

I'll investigate this further!

**Comment by Owen1212055** [comment]
@galexrt Found the issue and should be resolved now. 

This PR should have most major issues all fixed up, please report any new ones you found here.
Other than that, it's nearly ready!

**Comment by Owen1212055** [comment]
Current Todo:
- Looking into possible saving issues
- Investigating some reports where default biome does not work anymore.

**Comment by Owen1212055** [comment]
Major problems have been discovered with supporting old versions of Minecraft (1.17)

The current version for "world versions" causes worlds to be serialized under version 0x07 in 1.17, however, the code that handles serialization caused issues for these world versions...
So, we gotta do some digging here.

**Comment by Owen1212055** [comment]
World saving/loading doesn't seem to be working on 1.17 currently ^

**Comment by Owen1212055** [comment]
**⚠️PLEASE MAKE SURE YOUR WORLDS ARE BACKED UP, THIS IS A MAJOR CHANGE ⚠️**

### World saving has now been completely redone, with the strategy being shifted in order to focus on removing some of these bugs.

1. World saving is no longer done asynchronously
- This is very unsafe and could have been the reason for "mysterious" corruption
- Should fix some errors that were thrown due to certain entities being saved async
2. World saving is now done over multiple ticks
- This causes the "time" it takes for a world to save to appear much longer (this is however untrue but is simply the delay between ticks). This however ensures your server does not lag due to chunk saving. Currently, each world has 200 ms per tick for saving, these values may be tweaked over time.
3. Moving towards saving using nms backed entities instead of api ones.
- This is a more technical change, but the idea is to instead directly refer to nms instead of going through api objects. This can be seen with 1.18 and how entities were changed to be per world, however I am not sure if I am happy with this solution yet. 


It should be noted that creating empty worlds is also a bit slower now and this is because it shares the logic between normal MC worlds. This will be improved in the future.\

**⚠️⚠️ Please test this change on test servers first, please report any saving issues that may have arisen from this. ⚠️⚠️**

**Comment by Owen1212055** [comment]
Working on a fix towards #112

It currently is  NOT TESTED and will  NOT BE FUNCTIONAL.

**Comment by Owen1212055** [comment]
Fixed https://github.com/Paul19988/Advanced-Slime-World-Manager/issues/112 fully with unloaded chunks

Tested on 1.17
Needs to be tested on: 1.18/1.18.1

**Pull request merged**
