### PR TITLE
fix: unload command not working

### PR DESCRIPTION
**Pull request by ianlibanio**
Fix unload command not working when there were no players on the world.

### CODE REVIEW

**Comment by ComputerNerd100** [comment]
This PR doesn't seem fundamentally different from the existing code - it's just the same code written slightly differently.
Please feel free to reopen this PR if I'm missing something here, but this doesn't appear to actually change any code,

**Comment by ComputerNerd100** [comment]
@ianlibanio My apologies for closing this prematurely. With further review, Paul identified the fix your code was actually doing was due to us only unlocking the world if it had no players in it.
We'll resolve this one internally. Please try and keep PRs concise and clear in the future - some comments on the PR explaining why you've made the changes you have are very helpful when we're trying to review PRs, especially when like this the change wasn't obvious at first sight. Thanks for the contribution though as it did help identify a bug :)

**Comment by ianlibanio** [comment]
@ComputerNerd100 Hi, so I tought you would understand by the description "Fix unload command not working when there were no players on the world.". Thanks.

**Comment by tatteaid** [comment]
> @ComputerNerd100 Hi, so I tought you would understand by the description "Fix unload command not working when there were no players on the world.". Thanks.

"Some comments on the PR explaining why you've made the changes you have are very helpful when we're trying to review PRs, especially when like this the change wasn't obvious at first sight."

**Pull request closed without merging**
