### PR TITLE
fix: unload command not working (#127)

### PR DESCRIPTION
**Pull request by ianlibanio**
When running the unload command without someone on the island, the command wouldn't work.

This PR fix this issue.

### CODE REVIEW

**Review by iag0bezz — CHANGES_REQUESTED** [review]
Duplicated method at line 67 `players.forEach(player -> player.teleportAsync(spawnLocation));`

**Comment by ianlibanio** [comment]
Already had saw it, fixing...

**Comment by ComputerNerd100** [comment]
@ianlibanio I think I can see that you intended this to go into your fork, not into upstream, but just wanted to let you know that I noticed in your code you're calling Bukkit.unloadWorld in your completableFuture.thenRun block without wrapping in Bukkit.getScheduler.runTask - this will result in modifying the worlds off the main thread. The Bukkit API is *not* thread-safe, and this may result in unexpected behaviour. Hope this helps :)

**Comment by ianlibanio** [comment]
@ComputerNerd100 hi, so the PR is for here, but noticed those mistakes, so I'll create it again fixing this.

**Pull request closed without merging**
