### PR TITLE
Fix/1.19.2 world importer

### PR DESCRIPTION
**Pull request by LedariaTim1**
[#] Fixed a bug which threw an error because PosY object is sometimes a byte instead of an int after upgrading from paper

[#] World version corrected, is in the 1.19.2 still 0x08

### CODE REVIEW

**Comment by Owen1212055** [comment]
I’m a bit worried about changing the world version like that. I’m not sure if we can do that. Does it work fine still with importing old 1.19.2 worlds?

**Comment by LedariaTim1** [comment]
image
Yes, I have generated a new 1.19.2 world, unloaded it and imported it with aswm import. If I still output the world version, I get back 8. At the very beginning of the WorldImporter Class it also says that the WorldVersion has not changed to 1.19.2.

Originally I encountered the problem because I wanted to import arenas from our build server for testing and I got the message invalid version.
image
image

**Comment by Owen1212055** [comment]
Well, are you able to load previous 1.19.2 SLIME worlds? I worry because worlds that are slaved will have a different version number now. But yeah nothing has rly changed so idk why we needed to update the version number anyways.

**Comment by LedariaTim1** [comment]
i just tested this, yes a slime world created in 1.19.2 with the previous version of the plugin i can still load with the plugin version from my pull request and is also loaded automatically on server startup. Do you have a slime world I should try if it also loads?

**Comment by Owen1212055** [comment]
Thanks for the contribution :)

**Pull request merged**
