### PR TITLE
1.19.2 support

### PR DESCRIPTION
**Pull request by amadeusmz**

### CODE REVIEW

**Comment by Owen1212055** [comment]
Check the classmodifier resources, you need to add new classmodifiers.

**Comment by amadeusmz** [comment]
the classmodifier nms version remains the same v1_19_R1

**Comment by Owen1212055** [comment]
So it works fine with the current classmodifier? Just worried cause obfuscated names might change.

**Comment by amadeusmz** [comment]
yes, world creation/loading/cloning works for 1.19.2

**Comment by Codestech1** [comment]
When I import world it thinks my world is in newer version, but world version is 1.19.2.

**Pull request merged**
