### PR TITLE
code refeactoring.

### PR DESCRIPTION
**Pull request by portlek**
the p.r. includes
- new configuration library, remove the old one because of the stupid bugs.(the null section)
- tab indent size to 2.
- added github actions to secure p.r. and commit merging.
- added dependabot to check for update of dependencies.
- added @NotNull and @Nullable annotations to api and other places to tell developers 
- move the nms modules into main slimeworldmanager-nms module.
- updated all dependencies.
- added missing javadocs for api module.
- used more lombok.

the p.r. does not include
- any api or configuration changes.

it doesn't matter if you accept the p.r. i will use this p.r. on my projects.

### CODE REVIEW

**Review by Paul19988 — CHANGES_REQUESTED** [review]
- Please remove your .idea files from the PR.
- Is it intentional to give the root pom.xml a parent of "io.github.portlek"?

I will re-review after these changes have been made.

**Comment by portlek** [comment]
> * Please remove your .idea files from the PR.
> * Is it intentional to give the root pom.xml a parent of "io.github.portlek"?
> 
> I will re-review after these changes have been made.

yes, it's a [parent pom](https://github.com/portlek/depp/) which has dependencies and its versions. so its allow you to add the dependencies with artifact id and group id.
for the .idea files, it has code style files and inspection files which allow you to edit the code easily. for example you can do:

`ctrl + alt + shift + L`

for the cleaning up + optimizing imports + rearrangement the codes.

**Comment by CDFN** [comment]
I agree with Paul, imo the parent pom isn't necessary here. Also I think reformatting code should be in another PR, once this one is merged. Diff is really large so it's hard to review it.

**Comment by portlek** [comment]
yea i agree too, but i'll use it in this way. as i said it doesn't matter its merged or not. if you not happy with the PR i/you can close it anyway.

**Pull request closed without merging**
